name: clvision-challenge
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.1=py_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py38h32f6830_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_1000
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.9.1=h8a8886c_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py38h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.10.0=py38h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=hf484d3e_1000
  - importlib_metadata=1.5.0=py38_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py38h5ca1d4c_0
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py38_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter_client=6.0.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab=1.2.6=py_0
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py38hc9558a2_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - markupsafe=1.1.1=py38h516909a_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38hef1b27d_0
  - mistune=0.8.4=py38h516909a_1000
  - mkl=2020.0=166
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py38hfd86e86_0
  - notebook=6.0.3=py38_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.1=py38h0573a6f_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.0.0=py38hb39fc2d_0
  - pip=20.0.2=py38_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - psutil=5.6.7=py38h7b6447c_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.15.7=py38h516909a_0
  - python=3.8.1=h0371630_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.4.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pyzmq=19.0.0=py38h1768529_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py_0
  - setuptools=45.2.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h7b6447c_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py38_cu101
  - tornado=6.0.3=py38h516909a_4
  - traitlets=4.3.3=py38_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.0.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - albumentations==0.4.3
    - cachetools==4.0.0
    - chardet==3.0.4
    - efficientnet-pytorch==0.6.3
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.2
    - idna==2.9
    - imageio==2.8.0
    - imgaug==0.2.6
    - markdown==3.2.1
    - munch==2.5.0
    - networkx==2.4
    - oauthlib==3.1.0
    - opencv-python-headless==4.2.0.32
    - pretrainedmodels==0.7.4
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pywavelets==1.1.1
    - pyyaml==5.3
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-image==0.16.2
    - scipy==1.4.1
    - tensorboard==2.1.0
    - torchsummary==1.5.1
    - tqdm==4.45.0
    - urllib3==1.25.8
    - werkzeug==1.0.0

