name: base
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py38_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - cffi=1.14.0=py38h2e261b9_0
  - chardet=3.0.4=py38_1003
  - conda=4.8.3=py38_0
  - conda-package-handling=1.6.0=py38h7b6447c_0
  - cryptography=2.8=py38h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.9.1=h8a8886c_1
  - idna=2.8=py38_1000
  - intel-openmp=2020.0=166
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py38hfd86e86_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1g=h7b6447c_0
  - pillow=7.1.2=py38hb39fc2d_0
  - pip=20.0.2=py38_1
  - psutil=5.7.0=py38h7b6447c_0
  - pycosat=0.6.3=py38h7b6447c_0
  - pycparser=2.19=py_0
  - pyopenssl=19.1.0=py38_0
  - pysocks=1.7.1=py38_0
  - python=3.8.1=h0371630_1
  - pytorch=1.5.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py38_1
  - ruamel_yaml=0.15.87=py38h7b6447c_0
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.6.0=py38_cu101
  - tqdm=4.42.1=py_0
  - urllib3=1.25.8=py38_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /opt/conda
